version: '3.1'

services:

  nginx:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./ShortLink:/var/www/html/
      - ./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm

  fpm:
    build:
      context: .
      dockerfile: docker/fpm.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./ShortLink:/var/www/html/
    links:
      - mysql

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: shortlink
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - shortlinkdb:/var/lib/mysql
    restart: always

volumes:
  shortlinkdb:
