version: '3.1'

services:

  nginx:
    image: nginx
    ports:
      - 8081:80
    volumes:
      - ./ShortLink:/var/www/html/
      - ./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - fpm

  fpm:
    build:
      context: .
      dockerfile: docker/fpm.Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./ShortLink:/var/www/html/
